import { RememberTokenRepositoryPort } from '../../domain/ports/RememberTokenRepositoryPort';
import { UserRepositoryPort } from '../../domain/ports/UserRepositoryPort';
import { TokenHasherPort } from '../../domain/ports/TokenHasherPort';
import { RefreshTokenRotatorPort } from '../../domain/ports/RefreshTokenRotatorPort';
import { LoggerPort } from '../../domain/ports/LoggerPort';
import { RememberToken } from '../../domain/entities/RememberToken';
import { REFRESH_TOKEN_GRACE_SECONDS } from '../../domain/entities/RefreshTokenGrace';
import { RefreshTokenRotationLostRaceError } from '../../domain/exceptions/RefreshTokenRotationLostRaceError';
import { UserDTO } from '../dtos/UserDTO';

export interface RefreshSessionInput {
  presentedPlainToken: string;
  // Pre-generated by the caller (infrastructure layer owns crypto — mirrors
  // RotateRefreshTokenUseCase's own `newPlainToken` parameter). Unused
  // unless the outcome is 'rotated'.
  newPlainToken: string;
}

export type RefreshSessionResult =
  | { outcome: 'rejected' }
  // Row 6. Payload-free on purpose: the HTTP response is byte-identical to
  // 'rejected' (proposal decision 4), and withholding familyId makes leaking
  // it into the 401 body structurally impossible (design.md D2).
  | { outcome: 'reuse-detected' }
  // `familyExpiresAt` is the family's absolute deadline, inherited across
  // rotations rather than slid (design.md). The caller needs it because the
  // access COOKIE must live as long as the session does — without it, every
  // refresh rewrote `m3d_auth` with the 2h default and silently downgraded a
  // remembered session, leaving logout with nothing to revoke from.
  | { outcome: 'grace'; user: UserDTO; familyId: string; familyExpiresAt: Date }
  | {
      outcome: 'rotated';
      user: UserDTO;
      familyId: string;
      familyExpiresAt: Date;
      refreshToken: RememberToken;
    };

const toUserDTO = (user: {
  idUser: number;
  firstName: string;
  lastName: string;
  email: string;
  image: string | null;
  idRole?: number | null;
  category?: string | null;
}): UserDTO => ({
  idUser: user.idUser,
  firstName: user.firstName,
  lastName: user.lastName,
  email: user.email,
  image: user.image,
  idRole: user.idRole,
  category: user.category,
});

// design.md D2's lookup-order branch table, driven by one `findByHash` read
// then a branch — NOT the six-row table's original (mis-scoped) home,
// RotateRefreshTokenUseCase; see that file's header comment.
export class RefreshSessionUseCase {
  constructor(
    private readonly rememberTokenRepo: RememberTokenRepositoryPort,
    private readonly userRepo: UserRepositoryPort,
    private readonly tokenHasher: TokenHasherPort,
    private readonly rotateRefreshTokenUseCase: RefreshTokenRotatorPort,
    private readonly logger: LoggerPort
  ) {}

  async execute(input: RefreshSessionInput): Promise<RefreshSessionResult> {
    const presentedHash = this.tokenHasher.hash(input.presentedPlainToken);
    const current = await this.rememberTokenRepo.findByHash(presentedHash);

    if (!current) {
      return { outcome: 'rejected' }; // row 1: absent
    }

    // Row 2: logout beats grace — checked before superseded/expiry so a
    // revoked family is terminal regardless of grace-window timing.
    if (current.revokedAt) {
      return { outcome: 'rejected' };
    }

    if (new Date() > current.expiryDate) {
      return { outcome: 'rejected' }; // row 3: expired
    }

    if (!current.supersededAt) {
      // Row 4: current -> rotate. A lost race means someone else rotated
      // between our read and the claim; re-read OUTSIDE the aborted
      // transaction (design.md D1) to resolve grace vs. reject on fresh data.
      try {
        const successor = await this.rotateRefreshTokenUseCase.execute(current, input.newPlainToken);
        const user = await this.userRepo.findById(current.idUser);
        if (!user || !current.familyId) {
          return { outcome: 'rejected' };
        }
        return {
          outcome: 'rotated',
          user: toUserDTO(user),
          familyId: current.familyId,
          familyExpiresAt: current.expiryDate,
          refreshToken: successor,
        };
      } catch (error) {
        if (error instanceof RefreshTokenRotationLostRaceError) {
          return this.resolveGraceOrReject(presentedHash);
        }
        throw error;
      }
    }

    // Rows 5/6: already superseded — grace hit or replay past grace.
    return this.resolveGraceOrReject(presentedHash, current);
  }

  private async resolveGraceOrReject(
    presentedHash: string,
    alreadyRead?: RememberToken
  ): Promise<RefreshSessionResult> {
    const row = alreadyRead ?? (await this.rememberTokenRepo.findByHash(presentedHash));

    if (!row || row.revokedAt || !row.supersededAt || !row.familyId) {
      return { outcome: 'rejected' };
    }

    const graceDeadline = new Date(row.supersededAt.getTime() + REFRESH_TOKEN_GRACE_SECONDS * 1000);
    if (new Date() > graceDeadline) {
      // Row 6: replay past grace -> reuse detection (design.md D2/D3/D6).
      // No try/catch: a revocation failure must propagate as a 500, never
      // be swallowed into this 401-shaped outcome (design.md D3) — a
      // silent 401 while a known-compromised family survives is worse than
      // an inference an attacker can only draw while the DB is already
      // failing every other request too.
      const revokedRows = await this.rememberTokenRepo.revokeFamily(row.familyId);

      // Revoke first, then log, so `revokedRows` reflects what actually
      // happened rather than an assumption (design.md D6).
      this.logger.warn(
        {
          event: 'refresh_token_reuse_detected',
          familyId: row.familyId,
          userId: row.idUser,
          supersededAt: row.supersededAt.toISOString(),
          ageSeconds: (Date.now() - row.supersededAt.getTime()) / 1000,
          revokedRows,
          timestamp: new Date().toISOString(),
        },
        `Refresh token reuse detected for family ${row.familyId}`
      );

      return { outcome: 'reuse-detected' };
    }

    if (!row.successorHash) {
      return { outcome: 'rejected' };
    }

    const successor = await this.rememberTokenRepo.findByHash(row.successorHash);
    if (!successor || successor.revokedAt || new Date() > successor.expiryDate) {
      return { outcome: 'rejected' };
    }

    const user = await this.userRepo.findById(row.idUser);
    if (!user) {
      return { outcome: 'rejected' };
    }

    return {
      outcome: 'grace',
      user: toUserDTO(user),
      familyId: row.familyId,
      familyExpiresAt: row.expiryDate,
    }; // row 5
  }
}
