import { RememberTokenRepositoryPort } from '../../domain/ports/RememberTokenRepositoryPort';
import { UserRepositoryPort } from '../../domain/ports/UserRepositoryPort';
import { TokenHasherPort } from '../../domain/ports/TokenHasherPort';
import { RefreshTokenRotatorPort } from '../../domain/ports/RefreshTokenRotatorPort';
import { RememberToken } from '../../domain/entities/RememberToken';
import { REFRESH_TOKEN_GRACE_SECONDS } from '../../domain/entities/RefreshTokenGrace';
import { RefreshTokenRotationLostRaceError } from '../../domain/exceptions/RefreshTokenRotationLostRaceError';
import { UserDTO } from '../dtos/UserDTO';

export interface RefreshSessionInput {
  presentedPlainToken: string;
  // Pre-generated by the caller (infrastructure layer owns crypto — mirrors
  // RotateRefreshTokenUseCase's own `newPlainToken` parameter). Unused
  // unless the outcome is 'rotated'.
  newPlainToken: string;
}

export type RefreshSessionResult =
  | { outcome: 'rejected' }
  | { outcome: 'grace'; user: UserDTO; familyId: string }
  | { outcome: 'rotated'; user: UserDTO; familyId: string; refreshToken: RememberToken };

const toUserDTO = (user: {
  idUser: number;
  firstName: string;
  lastName: string;
  email: string;
  image: string | null;
  idRole?: number | null;
  category?: string | null;
}): UserDTO => ({
  idUser: user.idUser,
  firstName: user.firstName,
  lastName: user.lastName,
  email: user.email,
  image: user.image,
  idRole: user.idRole,
  category: user.category,
});

// design.md D2's lookup-order branch table, driven by one `findByHash` read
// then a branch — NOT the six-row table's original (mis-scoped) home,
// RotateRefreshTokenUseCase; see that file's header comment.
export class RefreshSessionUseCase {
  constructor(
    private readonly rememberTokenRepo: RememberTokenRepositoryPort,
    private readonly userRepo: UserRepositoryPort,
    private readonly tokenHasher: TokenHasherPort,
    private readonly rotateRefreshTokenUseCase: RefreshTokenRotatorPort
  ) {}

  async execute(input: RefreshSessionInput): Promise<RefreshSessionResult> {
    const presentedHash = this.tokenHasher.hash(input.presentedPlainToken);
    const current = await this.rememberTokenRepo.findByHash(presentedHash);

    if (!current) {
      return { outcome: 'rejected' }; // row 1: absent
    }

    // Row 2: logout beats grace — checked before superseded/expiry so a
    // revoked family is terminal regardless of grace-window timing.
    if (current.revokedAt) {
      return { outcome: 'rejected' };
    }

    if (new Date() > current.expiryDate) {
      return { outcome: 'rejected' }; // row 3: expired
    }

    if (!current.supersededAt) {
      // Row 4: current -> rotate. A lost race means someone else rotated
      // between our read and the claim; re-read OUTSIDE the aborted
      // transaction (design.md D1) to resolve grace vs. reject on fresh data.
      try {
        const successor = await this.rotateRefreshTokenUseCase.execute(current, input.newPlainToken);
        const user = await this.userRepo.findById(current.idUser);
        if (!user || !current.familyId) {
          return { outcome: 'rejected' };
        }
        return { outcome: 'rotated', user: toUserDTO(user), familyId: current.familyId, refreshToken: successor };
      } catch (error) {
        if (error instanceof RefreshTokenRotationLostRaceError) {
          return this.resolveGraceOrReject(presentedHash);
        }
        throw error;
      }
    }

    // Rows 5/6: already superseded — grace hit or replay past grace.
    return this.resolveGraceOrReject(presentedHash, current);
  }

  private async resolveGraceOrReject(
    presentedHash: string,
    alreadyRead?: RememberToken
  ): Promise<RefreshSessionResult> {
    const row = alreadyRead ?? (await this.rememberTokenRepo.findByHash(presentedHash));

    if (!row || row.revokedAt || !row.supersededAt || !row.familyId) {
      return { outcome: 'rejected' };
    }

    const graceDeadline = new Date(row.supersededAt.getTime() + REFRESH_TOKEN_GRACE_SECONDS * 1000);
    if (new Date() > graceDeadline) {
      return { outcome: 'rejected' }; // row 6: replay past grace
    }

    if (!row.successorHash) {
      return { outcome: 'rejected' };
    }

    const successor = await this.rememberTokenRepo.findByHash(row.successorHash);
    if (!successor || successor.revokedAt || new Date() > successor.expiryDate) {
      return { outcome: 'rejected' };
    }

    const user = await this.userRepo.findById(row.idUser);
    if (!user) {
      return { outcome: 'rejected' };
    }

    return { outcome: 'grace', user: toUserDTO(user), familyId: row.familyId }; // row 5
  }
}
